name: Build and deploy Python simple app to Azure Web App

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Name of the Azure Web App'
        required: true
        default: 'app-test-3p'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Create and start virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r ./src/SimpleWeb/requirements.txt
      
      - name: Zip artifact for deployment
        run: zip -j release.zip ./src/SimpleWeb/*
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-simple-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-simple-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ github.event.inputs['app-name'] }}
          slot-name: 'Production'
